"""add base_currency to users

Revision ID: 048832268951
Revises: e75c8414e614
Create Date: 2026-07-15 11:56:09.006777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048832268951'
down_revision: Union[str, Sequence[str], None] = 'e75c8414e614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_currency', sa.String(length=3), server_default='TWD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_currency')
    # ### end Alembic commands ###
