"""add transfer table

Revision ID: 076f6b840d71
Revises: 65498a45041b
Create Date: 2026-08-25 15:32:54.010011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076f6b840d71'
down_revision: Union[str, Sequence[str], None] = '65498a45041b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_account_id', sa.Integer(), nullable=False),
    sa.Column('destination_account_id', sa.Integer(), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('destination_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    # ### end Alembic commands ###
