"""add server_default to recurring_transactions.updated_at

Revision ID: 3bd9610abedb
Revises: 1bfb6692fe20
Create Date: 2026-09-15 17:15:43.983077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd9610abedb'
down_revision: Union[str, Sequence[str], None] = '1bfb6692fe20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurring_transactions', 'updated_at',
                    server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurring_transactions', 'updated_at',
                    server_default=None)
    # ### end Alembic commands ###
