"""add currency snapshot columns to transactions

Revision ID: 65498a45041b
Revises: 9bb834cfc392
Create Date: 2026-07-22 10:05:46.266453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65498a45041b'
down_revision: Union[str, Sequence[str], None] = '9bb834cfc392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('exchange_rate_to_base', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('transactions', sa.Column('base_currency_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    op.execute("UPDATE transactions SET exchange_rate_to_base = 1, base_currency_amount = amount")

    op.alter_column('transactions', 'exchange_rate_to_base', nullable=False)
    op.alter_column('transactions', 'base_currency_amount', nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'base_currency_amount')
    op.drop_column('transactions', 'exchange_rate_to_base')
    # ### end Alembic commands ###
